exports.category_stub = [
  {
    "id": 0,
    "message": null,
    "errorCode": null,
    "verNo": 0,
    "code": "A",
    "description": "Promotional Retail",
    "type": 0,
    "intCalcMethod": 0,
    "intRate": 0,
    "intRateBasis": 0,
    "calcDueInt": "\u0000",
    "intProjDateType": 0,
    "minPayPerc": 0,
    "curPrio": 0,
    "prvPrio": 0,
    "oldPrio": 0,
    "interestTypeCode": 0,
    "sysDef": "\u0000",
    "instId": 0
  },
  {
    "id": 0,
    "verNo": 0,
    "code": "AAA",
    "description": "Promotional Retail",
    "type": 0,
    "intCalcMethod": 0,
    "intRate": 0,
    "intRateBasis": 0,
    "calcDueInt": "\u0000",
    "intProjDateType": 0,
    "minPayPerc": 0,
    "curPrio": 0,
    "prvPrio": 0,
    "oldPrio": 0,
    "interestTypeCode": 0,
    "sysDef": "\u0000",
    "instId": 0,
    "message": null,
    "errorCode": null
  }
]
